# Generated by Django 2.1.7 on 2019-03-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190312_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemID', models.IntegerField()),
                ('MatchingItemID', models.IntegerField()),
                ('ParentPartNo', models.CharField(max_length=20)),
                ('MatchingPartNo', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='linkedProductID',
        ),
    ]
