# Generated by Django 2.1.7 on 2019-03-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190315_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipg',
            name='Code',
            field=models.CharField(max_length=10),
        ),
    ]
