# Generated by Django 2.1.7 on 2019-03-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190315_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipg',
            name='Description',
            field=models.CharField(max_length=50),
        ),
    ]
