# Generated by Django 2.1.7 on 2019-03-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerID', models.IntegerField()),
                ('address1', models.CharField(max_length=20)),
                ('address2', models.CharField(max_length=20)),
                ('town', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerCode', models.CharField(max_length=20)),
                ('companyName', models.CharField(max_length=20)),
                ('proforma', models.BooleanField()),
                ('billingaddressID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesType', models.CharField(max_length=20)),
                ('customerID', models.IntegerField()),
                ('itemID', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='IPG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=50)),
                ('EorH', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Matched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemID', models.IntegerField()),
                ('MatchingItemID', models.IntegerField()),
                ('ParentPartNo', models.CharField(max_length=20)),
                ('MatchingPartNo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.IntegerField()),
                ('cdn', models.CharField(max_length=20)),
                ('filename', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDateTime', models.DateTimeField(auto_created=True)),
                ('customerID', models.IntegerField()),
                ('addressID', models.IntegerField()),
                ('orderStatus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineNo', models.IntegerField()),
                ('itemID', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemno', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('description2', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('colour', models.CharField(max_length=50)),
                ('manufacturerCode', models.CharField(max_length=50)),
                ('Product_Category', models.CharField(max_length=20)),
                ('RRP', models.DecimalField(decimal_places=2, max_digits=6)),
                ('SSP', models.DecimalField(decimal_places=2, max_digits=6)),
                ('FreeStock', models.IntegerField()),
                ('ItemSpec1', models.CharField(max_length=69)),
                ('ItemSpec2', models.CharField(max_length=69)),
                ('ItemSpec3', models.CharField(max_length=69)),
                ('ItemSpec4', models.CharField(max_length=69)),
                ('ItemSpec5', models.CharField(max_length=69)),
                ('ItemSpec6', models.CharField(max_length=69)),
                ('ItemSpec7', models.CharField(max_length=69)),
                ('ItemSpec8', models.CharField(max_length=69)),
                ('ItemSpec9', models.CharField(max_length=69)),
                ('ItemSpec10', models.CharField(max_length=69)),
                ('TI', models.IntegerField()),
                ('HI', models.IntegerField()),
                ('Item_Height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Item_Length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Item_Width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ProductPaging_Height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ProductPaging_Length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ProductPaging_Width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('CartonHeight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('CartonLength', models.DecimalField(decimal_places=2, max_digits=6)),
                ('CartonWidth', models.DecimalField(decimal_places=2, max_digits=6)),
                ('palletQty', models.IntegerField()),
                ('cartonQty', models.IntegerField()),
                ('restockDate', models.DateField()),
                ('IPGID', models.IntegerField()),
            ],
        ),
    ]
