# Generated by Django 2.1.7 on 2019-03-13 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='restockDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
