# Generated by Django 2.1.7 on 2019-04-30 13:16

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190429_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Imagetest',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
