# Generated by Django 2.1.7 on 2019-03-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
