# Generated by Django 2.1.7 on 2019-03-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesType', models.CharField(max_length=20)),
                ('customerID', models.IntegerField()),
                ('itemID', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.IntegerField()),
                ('cdn', models.CharField(max_length=20)),
                ('filename', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDateTime', models.DateTimeField(auto_created=True)),
                ('customerID', models.IntegerField()),
                ('addressID', models.IntegerField()),
                ('orderStatus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineNo', models.IntegerField()),
                ('itemID', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='CartonHeight',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='CartonLength',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='CartonWidth',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='FreeStock',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='HI',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ItemSpec1',
            field=models.CharField(default=-1, max_length=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ItemSpec10',
            field=models.CharField(default=-1, max_length=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ItemSpec2',
            field=models.CharField(default=-1, max_length=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ItemSpec3',
            field=models.CharField(default=-1, max_length=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ItemSpec4',
            field=models.CharField(default=-1, max_length=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ItemSpec5',
            field=models.CharField(default=-1, max_length=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ItemSpec6',
            field=models.CharField(default=-1, max_length=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ItemSpec7',
            field=models.CharField(default=-1, max_length=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ItemSpec8',
            field=models.CharField(default=-1, max_length=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ItemSpec9',
            field=models.CharField(default=-1, max_length=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Item_Height',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Item_Length',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Item_Width',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ProductPaging_Height',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ProductPaging_Length',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ProductPaging_Width',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Category',
            field=models.CharField(default=-1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='RRP',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='SSP',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Ti',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='cartonQty',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='linkedProductID',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='palletQty',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
