# Generated by Django 2.1.7 on 2019-03-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190312_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=10)),
                ('Description', models.CharField(max_length=10)),
                ('EorH', models.CharField(max_length=10)),
            ],
        ),
    ]
