# Generated by Django 2.1.7 on 2019-05-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190430_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStatementRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('notified', models.BooleanField(default=False)),
                ('dateNotified', models.DateTimeField(default='1900-01-01')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('invoiceNo', models.CharField(max_length=20)),
                ('notified', models.BooleanField(default=False)),
                ('dateNotified', models.DateTimeField(default='1900-01-01')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.TextField(null=True),
        ),
    ]
