# Generated by Django 2.1.7 on 2019-03-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190312_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipg',
            name='ItemID',
            field=models.IntegerField(),
        ),
    ]
