# Generated by Django 2.1.7 on 2019-03-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_restockdate'),
        ('api', '0010_auto_20190312_1633'),
    ]

    operations = [
    ]
