# Generated by Django 2.1.7 on 2019-03-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20190315_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipg',
            old_name='ItemID',
            new_name='Code',
        ),
        migrations.AlterField(
            model_name='product',
            name='restockDate',
            field=models.DateField(),
        ),
    ]
