# Generated by Django 2.1.7 on 2019-03-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190315_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Ti',
            new_name='TI',
        ),
    ]
