# Generated by Django 2.1.7 on 2019-03-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190318_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlines',
            name='orderDateTime',
            field=models.DateTimeField(auto_created=True, default='1970-01-01T00:00'),
            preserve_default=False,
        ),
    ]
