# Generated by Django 2.1.7 on 2019-03-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_orderlines_orderdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlines',
            name='orderHeaderID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
