# Generated by Django 2.1.7 on 2019-03-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_customerprices_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='IPG',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
