# Generated by Django 2.1.7 on 2019-03-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_product_ipg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customerno',
            field=models.CharField(default=-1, max_length=20),
            preserve_default=False,
        ),
    ]
