# Generated by Django 2.1.7 on 2019-04-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190328_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='IPGID',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description2',
        ),
    ]
