# Generated by Django 2.1.7 on 2019-04-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190401_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='CatalogueTheme',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='IPG',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ItemSpec1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ItemSpec10',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ItemSpec2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ItemSpec3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ItemSpec4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ItemSpec5',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ItemSpec6',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ItemSpec7',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ItemSpec8',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ItemSpec9',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='itemno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturerCode',
            field=models.CharField(max_length=100),
        ),
    ]
