# Generated by Django 2.1.7 on 2019-04-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20190401_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Analysis2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='HI',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='TI',
            field=models.IntegerField(),
        ),
    ]
