# Generated by Django 2.1.7 on 2019-04-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190404_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Electrical_or_Housewares',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
