# Generated by Django 2.1.7 on 2019-04-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_product_electrical_or_housewares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='palletQty',
            field=models.IntegerField(null=True),
        ),
    ]
