# Generated by Django 2.1.7 on 2019-04-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20190404_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprices',
            old_name='itemID',
            new_name='itemno',
        ),
        migrations.RenameField(
            model_name='matched',
            old_name='ItemID',
            new_name='Matchingitemno',
        ),
        migrations.RemoveField(
            model_name='matched',
            name='MatchingItemID',
        ),
        migrations.RemoveField(
            model_name='media',
            name='itemID',
        ),
        migrations.RemoveField(
            model_name='orderlines',
            name='itemID',
        ),
        migrations.AddField(
            model_name='matched',
            name='itemno',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='itemno',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlines',
            name='itemno',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
