# Generated by Django 2.1.7 on 2019-04-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20190404_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprices',
            old_name='salesType',
            new_name='customerNo',
        ),
        migrations.RemoveField(
            model_name='customerprices',
            name='customerID',
        ),
        migrations.AddField(
            model_name='product',
            name='HighSell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerprices',
            name='itemno',
            field=models.CharField(max_length=20),
        ),
    ]
