# Generated by Django 2.1.7 on 2019-04-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20190405_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='email',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='customerID',
            new_name='customerNO',
        ),
        migrations.RemoveField(
            model_name='address',
            name='town',
        ),
    ]
