# Generated by Django 2.1.7 on 2019-04-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20190408_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='county',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='phoneNumber',
            field=models.CharField(max_length=30),
        ),
    ]
