# Generated by Django 2.1.7 on 2019-04-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20190408_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackInStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerNO', models.CharField(max_length=20)),
                ('itemno', models.CharField(max_length=100)),
                ('notified', models.BooleanField()),
                ('dateNotified', models.DateTimeField()),
            ],
        ),
    ]
