# Generated by Django 2.1.7 on 2019-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_backinstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backinstock',
            name='dateNotified',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='backinstock',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
