# Generated by Django 2.1.7 on 2019-04-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20190409_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='backinstock',
            name='username',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
