# Generated by Django 2.1.7 on 2019-04-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_backinstock_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderheader',
            name='customerID',
        ),
        migrations.AddField(
            model_name='orderheader',
            name='customerCode',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
