# Generated by Django 2.1.7 on 2019-04-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20190409_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Analysis1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
