# Generated by Django 2.1.7 on 2019-04-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_userprofile_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ElectricalRep',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='HousewaresRep',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='SalespersonCode',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
