# Generated by Django 2.1.7 on 2019-04-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
