# Generated by Django 2.1.7 on 2019-04-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20190412_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
