# Generated by Django 2.1.7 on 2019-04-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20190412_1422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPG',
        ),
    ]
