# Generated by Django 2.1.7 on 2019-04-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='CreditControlManager',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='HouseManager',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
