# Generated by Django 2.1.7 on 2019-04-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20190415_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_created=True)),
                ('customerCode', models.CharField(max_length=20)),
                ('itemno', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderlines',
            name='lineNo',
        ),
        migrations.AddField(
            model_name='backinstock',
            name='dateCreated',
            field=models.DateTimeField(auto_created=True, default=19000101),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
