# Generated by Django 2.1.7 on 2019-04-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20190425_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='CreditControlManager',
            field=models.CharField(default=-1, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ElectricalRep',
            field=models.CharField(default=-1, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='HouseManager',
            field=models.CharField(default=-1, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='HousewaresRep',
            field=models.CharField(default=-1, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='SalespersonCode',
            field=models.CharField(default=-1, max_length=20),
        ),
    ]
