# Generated by Django 2.1.7 on 2019-04-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20190425_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='dateCreated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='CreditControlManager',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ElectricalRep',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='HouseManager',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='HousewaresRep',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='SalespersonCode',
            field=models.CharField(max_length=20),
        ),
    ]
