# Generated by Django 2.1.7 on 2019-04-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20190426_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
