# Generated by Django 2.1.7 on 2019-04-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20190426_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backinstock',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='orderDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderlines',
            name='orderDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
