# Generated by Django 2.1.7 on 2019-04-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20190426_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backinstock',
            name='dateCreated',
            field=models.DateTimeField(),
        ),
    ]
