# Generated by Django 2.1.7 on 2019-04-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20190426_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backinstock',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
