# Generated by Django 2.1.7 on 2019-04-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20190426_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backinstock',
            name='dateCreated',
            field=models.DateTimeField(),
        ),
    ]
