# Generated by Django 2.1.7 on 2019-04-26 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_remove_backinstock_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='backinstock',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
